name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: Lint, Type check & Build
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4.2.2

      - uses: pnpm/action-setup@v4.1.0

      - uses: actions/setup-node@v4.4.0
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma client
        run: pnpm prisma generate

      - name: Lint & format
        run: pnpm biome check ./src

      - name: Typecheck
        run: pnpm tsc --noEmit

      - name: Tests
        run: pnpm test
